# Generated by Django 4.2 on 2023-09-24 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RetrievalAPI', '0004_rename_body_object_dadimg_object_momimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='dadImg',
            new_name='perImg',
        ),
        migrations.RemoveField(
            model_name='object',
            name='momImg',
        ),
    ]
