# Generated by Django 4.2 on 2023-10-18 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("RetrievalAPI", "0005_rename_dadimg_object_perimg_remove_object_momimg"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Object",
            new_name="Submission",
        ),
    ]
